### ISSUE TITLE
Use Case Diagram is crowded and difficult to read

### ISSUE THREAD

**Issue by vivian46959** [cpe308-309/winter-spring2017-AL#16]
The arrows are difficult to distinguish from one user to the next and clutters the content. The image is challenging to decipher and the reader needs more than a couple of minutes in order to understand the diagram. 

![oldusecasediagram](https://cloud.githubusercontent.com/assets/9358486/24021943/bfe421dc-0a60-11e7-9532-64e7d7fca3c2.png)

**Comment by vivian46959** [comment]
Here is an updated version of the use case diagram that is easier to read and comprehend.

![slochart use case diagram](https://cloud.githubusercontent.com/assets/9358486/24021996/1191b378-0a61-11e7-8d33-0f34a80160b5.png)

**Comment by gsocher** [comment]
Please no arrows in a use case diagram (just lines connecting actor and use case)!!! Extends and includes of use cases are dashed lines with arrows pointing to the included use case (<<includes>>) and to the extended use case (<<extends>>). Please see the chapter 'The Use Case Diagram' in UML@Classroom.

**Comment by vivian46959** [comment]
Fixed the arrows, extends, and includes. 

![slochart use case diagram](https://cloud.githubusercontent.com/assets/9358486/24036631/97e94d36-0ab7-11e7-84ef-d4da1d1b49fc.png)
