### ISSUE TITLE
Login HTML page

### ISSUE THREAD

**Issue by alexbcastana** [cpe308-309/winter-spring2017-AL#19]
The goal is to create a simple login front-end page. It will contain the name of the project, an email input text box, a password input text box, and a sign in button.

**Comment by alexbcastana** [comment]
As of 4/9/2017, a login page has been created with an email input, password input, and a sign in input button. The next step is to add the CSS to the form to organize and customize the login page.

**Comment by leklein** [comment]
Is #14 a duplicate of this issue?  And if so, can I close it (14)?

**Comment by alexbcastana** [comment]
You can close it.
Currently I have pushed the login page to master and it is connected to the single page routing architecture.
