### ISSUE TITLE
Back-End Developers: Servers, Application, and Databasing 

### ISSUE THREAD

**Issue by vivian46959** [cpe308-309/winter-spring2017-AL#3]
As the programmers creating the backbone of our entire website, it is important that the back-end developers know how to access a database and how it works. Furthermore, there should be an understanding of how Java is the foundational language for building the application. The languages to learn or understand are as follows: Java and SQL.

**Comment by brady-aiello** [comment]
I think we understand how it generally works, but ran out of time to integrate everything.
