### ISSUE TITLE
Error Checking Drag and Drop a Class into an Empty Column

### ISSUE THREAD

**Issue by vivian46959** [cpe308-309/winter-spring2017-AL#30]
In later implementations, we need to do error checking based on column. 

**Possible Errors:**
1. If the user is adding to a new quarter, i.e. column, a warning should pop up to let the user know that they need 12 units to be considered a full time student.
    * Allow users to not display the message.
2. If the student is graduating then they won't be allowed to take an extra quarter.
3. If the class has prerequisites then make sure that those prerequisites have already been finished.

**Comment by leklein** [comment]
No longer necessary
