### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by alexbcastana** [cpe308-309/winter-spring2017-AL#39]
Use Travis CI to build and test our commits to the master branch

**Comment by cevenhub** [comment]
Tested Travis-CI by performing a commit. Error occurred on Travis: 
"chmod: cannot access `gradlew': No such file or directory. The command "chmod +x gradlew" failed and exited with 1 during ."
Issue seems to be with .travis.yml

**Comment by cevenhub** [comment]
The .travis.yml file had the install lines added: 
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

This build on the travis site compiled successfully afterwards.
