### ISSUE TITLE
Look into possible Mongo bugs

### ISSUE THREAD

**Issue by cevenhub** [cpe308-309/winter-spring2017-AL#50]

**Comment by leklein** [comment]
How do we set up Mongo so we can run the app locally?

**Comment by cevenhub** [comment]
The application now runs with MongoDB dependency on Calvin-Mongo branch. Now checking to make sure server can be connected to.

**Comment by cevenhub** [comment]
The application now connects to the MongoDB server and can add and pull information from the database.
