### ISSUE TITLE
Restructure code involving databases to work with Mongo 

### ISSUE THREAD

**Issue by leklein** [cpe308-309/winter-spring2017-AL#51]
This may or may not be necessary depending on how mongo works; further discussion is needed.

**Comment by cevenhub** [comment]
The Course database is currently undergoing reformatting to match MongoDB code style. Reached obstacle of not being able to connect to Mongo persistent database, so the reformatted code cannot be tested right away.

**Comment by leklein** [comment]
Working off of Calvin's code, I got it working locally.  I'm going to run it on a personal heroku app before pushing to the main branch to make sure it works with the heroku addon I set up.

**Comment by cevenhub** [comment]
Databases have been functioning fine with Mongo. Closing issue.
