### ISSUE TITLE
Color the Catalog Courses Correctly

### ISSUE THREAD

**Issue by vivian46959** [cpe308-309/winter-spring2017-AL#64]
The database is now populated with various courses. However, the colors don't correspond to the correct education area. It may be difficult to find out whether a course is a support or not, since it's dependent on the major the student is pursuing.

**Comment by cevenhub** [comment]
Class and database structures were discussed to achieve this task. The main component is a database would contain two lists, one for major courses and one for support courses pertaining to a specific major. Currently working on implementing discussed classes.
